<a href="https://colab.research.google.com/github/Muntasir90629/Word-Embedding/blob/main/Implementing_Word_Embedding_Using_Keras_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [10]:

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:

### Vocabulary size
voc_size=10000




One Hot Representation

In [12]:

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6930, 2330, 7306, 6026], [6930, 2330, 7306, 748], [6930, 9315, 7306, 5229], [6926, 1362, 2957, 2229, 2702], [6926, 1362, 2957, 2229, 8219], [620, 6930, 5384, 7306, 7793], [2757, 763, 4107, 2229]]


Word Embedding Represntation

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6930 2330 7306 6026]
 [   0    0    0    0 6930 2330 7306  748]
 [   0    0    0    0 6930 9315 7306 5229]
 [   0    0    0 6926 1362 2957 2229 2702]
 [   0    0    0 6926 1362 2957 2229 8219]
 [   0    0    0  620 6930 5384 7306 7793]
 [   0    0    0    0 2757  763 4107 2229]]


In [16]:
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

[[[-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011
    0.0197908  -0.00958588  0.02930604 -0.04181115 -0.01263414]
  [-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011
    0.0197908  -0.00958588  0.02930604 -0.04181115 -0.01263414]
  [-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011
    0.0197908  -0.00958588  0.02930604 -0.04181115 -0.01263414]
  [-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011
    0.0197908  -0.00958588  0.02930604 -0.04181115 -0.01263414]
  [-0.04781035  0.01313787 -0.02543193  0.0211073  -0.01212833
    0.03337066 -0.03155385 -0.03922119 -0.04839313  0.00392472]
  [ 0.03926576  0.00578243 -0.04636549  0.00389466 -0.01808972
   -0.00423287 -0.04753672  0.00652884 -0.02663944 -0.02298102]
  [-0.00403395  0.03095032  0.04279194  0.03371611 -0.02901013
    0.02801502  0.01675019  0.04895537 -0.04738661  0.01342433]
  [ 0.04797287 -0.01254416  0.00697621 -0.04969912  0.03134027
   -0.04901987 -0.00441666  0.00690756 -0.039941

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 6930, 2330, 7306, 6026], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

[[-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011  0.0197908
  -0.00958588  0.02930604 -0.04181115 -0.01263414]
 [-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011  0.0197908
  -0.00958588  0.02930604 -0.04181115 -0.01263414]
 [-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011  0.0197908
  -0.00958588  0.02930604 -0.04181115 -0.01263414]
 [-0.02749335 -0.03879124 -0.04484865 -0.04702923 -0.02305011  0.0197908
  -0.00958588  0.02930604 -0.04181115 -0.01263414]
 [-0.04781035  0.01313787 -0.02543193  0.0211073  -0.01212833  0.03337066
  -0.03155385 -0.03922119 -0.04839313  0.00392472]
 [ 0.03926576  0.00578243 -0.04636549  0.00389466 -0.01808972 -0.00423287
  -0.04753672  0.00652884 -0.02663944 -0.02298102]
 [-0.00403395  0.03095032  0.04279194  0.03371611 -0.02901013  0.02801502
   0.01675019  0.04895537 -0.04738661  0.01342433]
 [ 0.04797287 -0.01254416  0.00697621 -0.04969912  0.03134027 -0.04901987
  -0.00441666  0.00690756 -0.03994194 -0.00797775]]
